GET http://localhost:3000/songs.json

### create
POST http://localhost:3000/songs.json
Content-Type: application/json

{
  "title": "another song",
  "artist": "another artist",
  "year": 100,
  "album": "an album"
}